version: "3.7"

services:
  # MySQL Database Container
  database:
    container_name: database
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: users_prod
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
      - ./api/_MySQL_Init_Script:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    restart: always
# For development database data to be stored in a docker volume
# called dbdata
volumes:
  dbdata:
